application:
  name: "LinkedIn Job Agent - Staging"
  version: "1.0.0"
  environment: "staging"
  debug: true

database:
  url: "sqlite:///./staging/data/db/jobs_staging.db"
  echo_sql: true
  pool_pre_ping: true
  cleanup_days: 30
  backup_enabled: true
  health_check_interval: 30

scraping:
  rate_limit_seconds: 10
  max_retries: 3
  timeout_seconds: 45
  headless: true
  user_agent: "LinkedIn-Job-Agent-Staging/1.0"

search:
  interval_minutes: 120
  max_results_per_search: 25
  max_applications_per_day: 5
  keywords:
    - "software engineer"
    - "python developer"
  locations:
    - "Remote"
  experience_levels:
    - "Mid-Senior level"

matching:
  minimum_score: 0.7
  experience_weight: 0.3
  skills_weight: 0.4
  location_weight: 0.2
  company_weight: 0.1

notifications:
  enabled: false
  sound: false
  desktop: false
  email: false

logging:
  level: "DEBUG"
  file: "staging/logs/app_staging.log"
  sql_logging: true
  performance_logging: true
  max_size_mb: 10
  backup_count: 5

monitoring:
  enabled: true
  performance_metrics: true
  health_checks: true
  log_file: "staging/logs/performance_staging.log"

deployment:
  timestamp: "2025-09-23T11:25:00Z"
  version: "1.0.0"
  feature: "US-001: Job Data Storage"
  environment: "staging"