environment:
  name: "staging"
  database_url: "sqlite:///staging/data/db/jobs_staging.db"
  log_level: "DEBUG"

scraping:
  enabled: true
  compliance_monitoring: true
  daily_limit_enforcement: true
  session_limit_enforcement: true

monitoring:
  enabled: true
  performance_tracking: true
  compliance_alerts: true
  error_tracking: true

alerts:
  tos_violation_threshold: 1
  error_rate_threshold: 0.1
  performance_threshold_ms: 50

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5